name: Publish Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    name: Generate site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: swift build

      - name: Generate Site
        run: swift run --skip-build

      - name: Upload Site artifact
        uses: actions/upload-artifact@v2
        with:
          name: Site
          path: Output

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: generate
    concurrency:
      group: deployment
    environment:
      name: Blog
      url: https://swiftwithadam.com
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download IPA artifact
        uses: actions/download-artifact@v2
        with:
          name: Site
          path: Output

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: blog
          FOLDER: Output
